services:
  backend:
    container_name: wavecare-backend

    build: .

    ports:
      - "3002:3002"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run start:dev

    restart: unless-stopped