import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.product.createMany({
    data: [
      // ===== VERAO | PRODUTOS =====
      {
        name: 'SunShield Shampoo',
        description: 'Limpeza suave com protecao UV para cabelos expostos ao sol e maresia.',
        price: 39.90,
        image: '/products/verao-produtos/verao-shampoo.png',
        stock: 100,
        season: 'verao',
        category: 'produto',
      },
      {
        name: 'SunShield Conditioner',
        description: 'Restaura a hidratacao dos fios apos exposicao solar, devolvendo maciez.',
        price: 42.80,
        image: '/products/verao-produtos/verao-condicionador.png',
        stock: 100,
        season: 'verao',
        category: 'produto',
      },
      {
        name: 'Summer Repair Mask',
        description: 'Tratamento intensivo de alta performance para recuperar fios danificados pelo sol e maresia.',
        price: 54.90,
        image: '/products/verao-produtos/verao-mascara.png',
        stock: 100,
        season: 'verao',
        category: 'produto',
      },
      {
        name: 'Heat And Sun Leave-In',
        description: 'Forma um filme protetor invisivel contra raios UV e calor excessivo, mantendo a definicao do cabelo.',
        price: 49.90,
        image: '/products/verao-produtos/verao-creme.png',
        stock: 100,
        season: 'verao',
        category: 'produto',
      },
      {
        name: 'Summer Definition Jelly',
        description: 'Definicao duradoura com efeito natural e toque leve.',
        price: 46.90,
        image: '/products/verao-produtos/verao-gelatina.png',
        stock: 100,
        season: 'verao',
        category: 'produto',
      },
      {
        name: 'Golden Shine Oil',
        description: 'Oleo nutritivo leve com brilho instantaneo. Controla o frizz, sela pontas e realca os cachos.',
        price: 44.90,
        image: '/products/verao-produtos/verao-oleo.png',
        stock: 100,
        season: 'verao',
        category: 'produto',
      },

      // ===== VERAO | KITS =====
      {
        name: 'Summer Essential Kit',
        description: 'O combo ideal para manter os fios protegidos, hidratados e luminosos durante o verao.',
        price: 129.90,
        image: '/products/verao-produtos/verao-kit-1.png',
        stock: 100,
        season: 'verao',
        category: 'kit',
      },
      {
        name: 'Summer Full Protection',
        description: 'Tratamento completo com protecao termica e solar, alem de limpeza e hidratacao profunda.',
        price: 189.90,
        image: '/products/verao-produtos/verao-kit-2.png',
        stock: 100,
        season: 'verao',
        category: 'kit',
      },
      {
        name: 'Summer Definition Duo',
        description: 'A dupla perfeita para definicao duradoura e controle do frizz no verao.',
        price: 89.90,
        image: '/products/verao-produtos/verao-kit-3.png',
        stock: 100,
        season: 'verao',
        category: 'kit',
      },
      {
        name: 'Summer Finishing Trio',
        description: 'O trio indispensavel para finalizar os fios durante o verao.',
        price: 109.90,
        image: '/products/verao-produtos/verao-kit-4.png',
        stock: 100,
        season: 'verao',
        category: 'kit',
      },
      {
        name: 'Summer Styling Duo',
        description: 'A combinacao ideal para modelar e nutrir os fios no verao.',
        price: 74.90,
        image: '/products/verao-produtos/verao-kit-5.png',
        stock: 100,
        season: 'verao',
        category: 'kit',
      },
      {
        name: 'Summer Total Protection',
        description: 'A experiencia completa de cuidado para o verao.',
        price: 249.90,
        image: '/products/verao-produtos/verao-kit-completo.png',
        stock: 100,
        season: 'verao',
        category: 'kit',
      },

      // ===== OUTONO | PRODUTOS =====
      {
        name: 'Autumn Nourish Shampoo',
        description: 'Limpeza suave com nutricao profunda para cabelos ressecados pela mudanca de estacao.',
        price: 39.90,
        image: '/products/outono-produtos/outono-shampoo.png',
        stock: 100,
        season: 'outono',
        category: 'produto',
      },
      {
        name: 'Autumn Nourish Conditioner',
        description: 'Restaura a hidratacao dos fios apos exposicao ao frio e ao vento, devolvendo maciez.',
        price: 42.80,
        image: '/products/outono-produtos/outono-condicionador.png',
        stock: 100,
        season: 'outono',
        category: 'produto',
      },
      {
        name: 'Autumn Repair Mask',
        description: 'Tratamento intensivo para recuperar fios danificados e ressecados pela queda de temperatura.',
        price: 54.90,
        image: '/products/outono-produtos/outono-mascara.png',
        stock: 100,
        season: 'outono',
        category: 'produto',
      },
      {
        name: 'Autumn Leave-In Cream',
        description: 'Forma uma barreira protetora contra o ressecamento, mantendo a definicao e o brilho dos fios.',
        price: 54.90,
        image: '/products/outono-produtos/outono-creme.png',
        stock: 100,
        season: 'outono',
        category: 'produto',
      },
      {
        name: 'Autumn Curl Styling Jelly',
        description: 'Definicao duradoura com efeito natural e toque leve para os dias de outono.',
        price: 46.90,
        image: '/products/outono-produtos/outono-gelatina.png',
        stock: 100,
        season: 'outono',
        category: 'produto',
      },
      {
        name: 'Autumn Shine Hair Oil',
        description: 'Oleo nutritivo com brilho ambar instantaneo. Controla o frizz, sela pontas e realca os cachos.',
        price: 34.90,
        image: '/products/outono-produtos/outono-oleo.png',
        stock: 100,
        season: 'outono',
        category: 'produto',
      },

      // ===== OUTONO | KITS =====
      {
        name: 'Autumn Essential Care Kit',
        description: 'O combo ideal para manter os fios protegidos, hidratados e luminosos durante o outono.',
        price: 119.90,
        image: '/products/outono-produtos/autumn-kit-1.png',
        stock: 100,
        season: 'outono',
        category: 'kit',
      },
      {
        name: 'Autumn Full Nutrition',
        description: 'Tratamento completo com nutricao profunda e protecao contra o frio e a secura da estacao.',
        price: 159.90,
        image: '/products/outono-produtos/autumn-kit-2.png',
        stock: 100,
        season: 'outono',
        category: 'kit',
      },
      {
        name: 'Autumn Definition Duo',
        description: 'A dupla perfeita para definicao duradoura e controle do frizz no outono.',
        price: 89.90,
        image: '/products/outono-produtos/autumn-kit-3.png',
        stock: 100,
        season: 'outono',
        category: 'kit',
      },
      {
        name: 'Autumn Finishing Trio',
        description: 'O trio indispensavel para finalizar os fios durante o outono.',
        price: 109.90,
        image: '/products/outono-produtos/autumn-kit-4.png',
        stock: 100,
        season: 'outono',
        category: 'kit',
      },
      {
        name: 'Autumn Styling Duo',
        description: 'A combinacao ideal para modelar e nutrir os fios no outono.',
        price: 74.90,
        image: '/products/outono-produtos/autumn-kit-5.png',
        stock: 100,
        season: 'outono',
        category: 'kit',
      },
      {
        name: 'Autumn Total Nutrition',
        description: 'A experiencia completa de cuidado e nutricao para o outono.',
        price: 249.90,
        image: '/products/outono-produtos/autumn-kit-completo.png',
        stock: 100,
        season: 'outono',
        category: 'kit',
      },

      // ===== INVERNO | PRODUTOS =====
      {
        name: 'Winter Deep Hydration Shampoo',
        description: 'Limpeza suave com nutricao intensiva para cabelos ressecados pelo frio e ar seco.',
        price: 46.90,
        image: '/products/inverno-produtos/inverno-shampoo.png',
        stock: 100,
        season: 'inverno',
        category: 'produto',
      },
      {
        name: 'Winter Soft Repair Conditioner',
        description: 'Restaura a maciez e hidratacao dos fios apos exposicao ao frio, vento e aquecedores.',
        price: 48.90,
        image: '/products/inverno-produtos/inverno-condicionador.png',
        stock: 100,
        season: 'inverno',
        category: 'produto',
      },
      {
        name: 'Winter Intense Repair Mask',
        description: 'Tratamento intensivo para recuperar fios danificados e ressecados pelo inverno rigoroso.',
        price: 56.90,
        image: '/products/inverno-produtos/inverno-mascara.png',
        stock: 100,
        season: 'inverno',
        category: 'produto',
      },
      {
        name: 'Winter Protective Leave-In Cream',
        description: 'Cria um escudo protetor contra o frio e o vento, mantendo a hidratacao e a definicao dos fios.',
        price: 42.90,
        image: '/products/inverno-produtos/inverno-creme.png',
        stock: 100,
        season: 'inverno',
        category: 'produto',
      },
      {
        name: 'Winter Curl Definition Gelatin',
        description: 'Definicao duradoura com protecao termica e efeito antifrizz para os dias mais frios.',
        price: 58.90,
        image: '/products/inverno-produtos/inverno-gelatina.png',
        stock: 100,
        season: 'inverno',
        category: 'produto',
      },
      {
        name: 'Winter Frost Shine Oil',
        description: 'Oleo nutritivo com aquecimento capilar e brilho instantaneo. Sela cuticulas e protege do frio.',
        price: 44.90,
        image: '/products/inverno-produtos/inverno-oleo.png',
        stock: 100,
        season: 'inverno',
        category: 'produto',
      },

      // ===== INVERNO | KITS =====
      {
        name: 'Winter Hydration Essential Kit',
        description: 'O combo ideal para manter os fios protegidos, hidratados e nutridos durante o inverno.',
        price: 129.90,
        image: '/products/inverno-produtos/inverno-kit1.png',
        stock: 100,
        season: 'inverno',
        category: 'kit',
      },
      {
        name: 'Winter Deep Care Kit',
        description: 'Tratamento completo com hidratacao profunda e protecao contra o frio e o ar seco.',
        price: 199.90,
        image: '/products/inverno-produtos/inverno-kit2.png',
        stock: 100,
        season: 'inverno',
        category: 'kit',
      },
      {
        name: 'Winter Curl Definition Duo',
        description: 'A dupla perfeita para definicao duradoura e protecao termica no inverno.',
        price: 89.90,
        image: '/products/inverno-produtos/inverno-kit3.png',
        stock: 100,
        season: 'inverno',
        category: 'kit',
      },
      {
        name: 'Winter Curl Definition Trio',
        description: 'O trio indispensavel para finalizar e proteger os fios durante o inverno.',
        price: 129.90,
        image: '/products/inverno-produtos/inverno-kit4.png',
        stock: 100,
        season: 'inverno',
        category: 'kit',
      },
      {
        name: 'Winter Shine Repair Kit',
        description: 'A combinacao ideal para modelar e nutrir os fios no inverno.',
        price: 84.90,
        image: '/products/inverno-produtos/inverno-kit5.png',
        stock: 100,
        season: 'inverno',
        category: 'kit',
      },
      {
        name: 'Winter Ultimate Care Kit',
        description: 'A experiencia completa de cuidado e nutricao para enfrentar o inverno.',
        price: 259.90,
        image: '/products/inverno-produtos/inverno-kitcompleto.png',
        stock: 100,
        season: 'inverno',
        category: 'kit',
      },

      // ===== PRIMAVERA | PRODUTOS =====
      {
        name: 'Bloom Shampoo',
        description: 'Limpeza suave com extrato de flores e protecao contra umidade excessiva da primavera.',
        price: 42.90,
        image: '/products/primavera-produtos/primavera-shampoo.png',
        stock: 100,
        season: 'primavera',
        category: 'produto',
      },
      {
        name: 'Bloom Conditioner',
        description: 'Restaura a maciez e o brilho dos fios com fragancia floral suave e duradoura.',
        price: 45.90,
        image: '/products/primavera-produtos/primavera-condicionador.png',
        stock: 100,
        season: 'primavera',
        category: 'produto',
      },
      {
        name: 'Bloom Repair Mask',
        description: 'Tratamento botanico intensivo para revitalizar fios ressecados pelo inverno com nutricao floral.',
        price: 56.90,
        image: '/products/primavera-produtos/primavera-mascara.png',
        stock: 100,
        season: 'primavera',
        category: 'produto',
      },
      {
        name: 'Floral Bloom Leave-In',
        description: 'Forma um veu protetor leve com essencias florais, controlando o frizz e devolvendo a definicao.',
        price: 49.90,
        image: '/products/primavera-produtos/primavera-creme.png',
        stock: 100,
        season: 'primavera',
        category: 'produto',
      },
      {
        name: 'Bloom Definition Jelly',
        description: 'Definicao duradoura com fixacao leve e perfume floral que dura o dia todo.',
        price: 48.90,
        image: '/products/primavera-produtos/primavera-gelatina.png',
        stock: 100,
        season: 'primavera',
        category: 'produto',
      },
      {
        name: 'Bloom Hair Oil',
        description: 'Oleo floral ultraleve com brilho instantaneo. Sela as pontas, controla o frizz e realca os cachos.',
        price: 41.90,
        image: '/products/primavera-produtos/primavera-oleo.png',
        stock: 100,
        season: 'primavera',
        category: 'produto',
      },

      // ===== PRIMAVERA | KITS =====
      {
        name: 'Spring Essential Kit',
        description: 'O combo ideal para renovar os fios na primavera, com limpeza, condicionamento e tratamento floral.',
        price: 129.90,
        image: '/products/primavera-produtos/primavera-kit-1.png',
        stock: 100,
        season: 'primavera',
        category: 'kit',
      },
      {
        name: 'Spring Full Bloom',
        description: 'Tratamento completo com protecao botanica e hidratacao profunda para os dias de renovacao.',
        price: 189.90,
        image: '/products/primavera-produtos/primavera-kit-2.png',
        stock: 100,
        season: 'primavera',
        category: 'kit',
      },
      {
        name: 'Spring Definition Duo',
        description: 'A dupla perfeita para definicao duradoura e controle do frizz nos dias de primavera.',
        price: 89.90,
        image: '/products/primavera-produtos/primavera-kit-3.png',
        stock: 100,
        season: 'primavera',
        category: 'kit',
      },
      {
        name: 'Spring Finishing Trio',
        description: 'O trio indispensavel para finalizar os fios com toque floral e brilho na primavera.',
        price: 109.90,
        image: '/products/primavera-produtos/primavera-kit-4.png',
        stock: 100,
        season: 'primavera',
        category: 'kit',
      },
      {
        name: 'Spring Styling Duo',
        description: 'A combinacao ideal para modelar e nutrir os fios com fragancia floral na primavera.',
        price: 69.90,
        image: '/products/primavera-produtos/primavera-kit-5.png',
        stock: 100,
        season: 'primavera',
        category: 'kit',
      },
      {
        name: 'Spring Total Bloom',
        description: 'A experiencia completa de florescimento para os seus fios na nova estacao.',
        price: 249.90,
        image: '/products/primavera-produtos/primavera-kit-completo.png',
        stock: 100,
        season: 'primavera',
        category: 'kit',
      },
    ],
  });

  console.log('Produtos cadastrados com sucesso!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });